With strings
lrecht/ParadigmComparison pull request #32
Opened 2020-10-15 11:43 UTC by Caspersn2

Quick and durty stop watch:
Before: 742
Now: 323

Kan godt ske at det andet måske er mere funktionelt??

2020-10-16 08:26 UTC, lrecht approved these changes

2020-10-19 11:09 UTC, lrecht requested changes

2020-10-19 11:09 UTC, lrecht commented on benchmarks/playing_cards/functional_f#/Program.fs
> +let Suit = [| "Diamonds";"Spades";"Hearts";"Clubs" |]
Er det ikke noget rod at vi bruger array i stedet for list?

2020-10-26 09:15 UTC, lrecht approved these changes

2020-10-30 08:00 UTC, AnneEjsing approved these changes

2020-10-30 08:01 UTC, lrecht approved these changes

2020-10-30 08:01 UTC, merged