Expression problem procedural f#
lrecht/ParadigmComparison pull request #68
Opened 2020-11-06 11:03 UTC by Caspersn2

2020-11-06 11:37 UTC, Nitram1995 requested changes
Vil mene, at det her er OOP

2020-11-06 11:37 UTC, Nitram1995 commented on benchmarks/expression_problem/procedural_f#/Program.fs
> +    abstract Print: string
Abstract? I procedural?

2020-11-06 11:37 UTC, Nitram1995 commented on benchmarks/expression_problem/procedural_f#/Program.fs
> +        this.Left.Eval + this.Right.Eval
Member functioner? I procedural

2020-11-06 11:37 UTC, Nitram1995 commented on benchmarks/expression_problem/procedural_f#/Program.fs
> +    interface IExpr with
nahhh

2020-11-09 10:37 UTC, Caspersn2 commented on benchmarks/expression_problem/procedural_f#/Program.fs
> +    interface IExpr with
nahhh?? Kan du ikke lide mit 100% procedural program?

2020-11-24 07:33 UTC, closed without merging