Bm game of life concurrent into master
lrecht/ParadigmComparison pull request #77
Opened 2020-11-09 11:38 UTC by AnneEjsing

2020-11-09 11:39 UTC, lrecht commented on benchmarks/game_of_life/functional_c#/Program.cs
> +            var initialStateRep = System.IO.File.ReadAllText("benchmarks/game_of_life/state256.txt")
```suggestion
            var initialStateRep = System.IO.File.ReadAllText("benchmarks/game_of_life_concurrent/state256.txt")

```

2020-11-09 11:40 UTC, lrecht commented on benchmarks/game_of_life/functional_f#/Program.fs
> +    let assocList = readFile "benchmarks/game_of_life/state256.txt"
```suggestion
    let assocList = readFile "benchmarks/game_of_life_concurrent/state256.txt"

```

2020-11-09 11:49 UTC, AnneEjsing commented on benchmarks/game_of_life_concurrent/functional_c#/Program.cs
> +                .ToImmutableArray();
```suggestion
            var initialStateRep = System.IO.File.ReadAllText("benchmarks/game_of_life_concurrent/state256.txt")
                .Select(x => x == '1')
                .ToImmutableArray();

```

2020-11-09 11:59 UTC, Caspersn2 approved these changes

2020-11-09 12:00 UTC, lrecht commented on benchmarks/game_of_life_concurrent/procedural_f#/Program.fs
> +        threadPool.[i].Join()
Burde det her ikke blive til Parallel.For?

2020-11-09 12:03 UTC, lrecht commented on benchmarks/game_of_life_concurrent/procedural_f#/Program.fs
> +let logicalProcessors = Environment.ProcessorCount;
```suggestion
```

2020-11-09 12:08 UTC, lrecht approved these changes

2020-11-09 12:20 UTC, Nitram1995 requested changes

2020-11-09 12:20 UTC, Nitram1995 commented on benchmarks/game_of_life_concurrent/oop_c#/Program.cs
> +                int k = (y + j + boardSize) % boardSize;
Er det ikke her vi skal gå lidt amok for at få det rigtige resultat fra modolu?
```suggestion
                int k = ((((y + j + boardSize) % boardSize) + boardSize) % boardSize);

```

2020-11-09 12:20 UTC, Nitram1995 commented on benchmarks/game_of_life_concurrent/oop_c#/Program.cs
> +                    int h = (x + i + boardSize) % boardSize;
```suggestion
                    int h = ((((x + i + boardSize) % boardSize) + boardSize) % boardSize);

```

2020-11-09 12:20 UTC, Nitram1995 commented on benchmarks/game_of_life_concurrent/procedural_c#/Program.cs
> +				int k = (y + j + height) % height;
```suggestion
				int k = ((((y + j + height) % height) + height) % height);
```

2020-11-09 12:20 UTC, Nitram1995 commented on benchmarks/game_of_life_concurrent/procedural_c#/Program.cs
> +					int h = (x + i + width) % width;
```suggestion
					int h = ((((x + i + width) % width) + width) % width);
```

2020-11-09 12:20 UTC, Nitram1995 commented on benchmarks/game_of_life_concurrent/procedural_f#/Program.fs
> +        let k = (y + j + height) % height
```suggestion
        let k = ((((y + j + height) % height) + height) % height)
```

2020-11-09 12:20 UTC, Nitram1995 commented on benchmarks/game_of_life_concurrent/procedural_f#/Program.fs
> +            let h = (x + i + width) % width;
```suggestion
            let h = ((((x + i + width) % width) + width) % width);
```

2020-11-09 12:21 UTC, Nitram1995 requested changes
Vi håndterer ikke modolu ens i alle implementationer

2020-11-13 10:22 UTC, Nitram1995 approved these changes

2020-11-13 10:22 UTC, merged