Kmeans oop c# into bm_kmeans
lrecht/ParadigmComparison pull request #79
Opened 2020-11-09 20:29 UTC by AnneEjsing

Implements k-means clustering both concurrently and sequentially in OOP C#.
Seq: ~21 sec
Par: ~8 sec

2020-11-11 13:11 UTC, Caspersn2 approved these changes

2020-11-12 12:42 UTC, Nitram1995 requested changes

2020-11-12 12:42 UTC, Nitram1995 commented on benchmarks/kmeans/oop_c#/Program.cs
> +                                .Select(p => new Cluster(p))
Kinda functional

2020-11-12 12:42 UTC, Nitram1995 commented on benchmarks/kmeans_concurrent/oop_c#/Program.cs
> +            points = File.ReadAllLines($"benchmarks/kmeans/points.txt")
```suggestion
            points = File.ReadAllLines($"benchmarks/kmeans_concurrent/points.txt")

```

2020-11-12 12:42 UTC, Nitram1995 commented on benchmarks/kmeans_concurrent/oop_c#/Program.cs
> +                                .ToArray();
Still kinda functional

2020-11-13 08:22 UTC, Nitram1995 approved these changes

2020-11-13 08:22 UTC, merged